# Generated by Django 3.2 on 2022-01-20 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='CSS',
            new_name='css',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='HTML',
            new_name='html',
        ),
    ]
